In [12]:
import torch
# 自动微分

x = torch.ones(5)
y = torch.zeros(3)
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w) + b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)


print(x)
print("-" * 70)
print(y)
print("-" * 70)
print(w)
print("-" * 70)
print(b)
print("-" * 70)
print(torch.matmul(x, w))
print("-" * 70)
print(z)
print("-" * 70)
print(loss)


tensor([1., 1., 1., 1., 1.])
----------------------------------------------------------------------
tensor([0., 0., 0.])
----------------------------------------------------------------------
tensor([[ 0.3280,  0.9689, -0.2634],
        [-0.6741, -2.4512, -0.7641],
        [-0.8769,  0.5888,  1.6131],
        [ 1.1363,  0.9397,  0.9337],
        [-0.2306,  0.2625,  0.5029]], requires_grad=True)
----------------------------------------------------------------------
tensor([ 0.6591, -0.8377, -0.5850], requires_grad=True)
----------------------------------------------------------------------
tensor([-0.3173,  0.3089,  2.0222], grad_fn=<SqueezeBackward4>)
----------------------------------------------------------------------
tensor([ 0.3418, -0.5288,  1.4372], grad_fn=<AddBackward0>)
----------------------------------------------------------------------
tensor(0.9974, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)


In [5]:
t = torch.tensor([
    [1, 2],
    [1, 2]
], dtype=torch.float)

t_ = torch.tensor([
    [1, 2],
    [1, 2]
], requires_grad=True, dtype=torch.float)

print(f"普通张量： \n{t}")
print("-" * 70)
print(f"自动微分张量: \n{t_}")

from torchvision.io import read_image


print(read_image("/home/SayMyName/桌面/GitHub/MyCode/DeepLearn/PyTorch/PyTorch_code_3_image_dir/test1_cat.jpg"))



普通张量： 
tensor([[1., 2.],
        [1., 2.]])
----------------------------------------------------------------------
自动微分张量: 
tensor([[1., 2.],
        [1., 2.]], requires_grad=True)
tensor([[[163, 163, 163,  ..., 174, 174, 175],
         [162, 162, 163,  ..., 173, 173, 174],
         [161, 162, 162,  ..., 172, 172, 173],
         ...,
         [140, 140, 141,  ...,  71,  70,  70],
         [140, 141, 143,  ...,  72,  71,  70],
         [143, 140, 138,  ...,  71,  71,  71]],

        [[169, 169, 169,  ..., 181, 181, 182],
         [168, 168, 169,  ..., 180, 180, 181],
         [167, 168, 168,  ..., 179, 179, 180],
         ...,
         [144, 144, 145,  ...,  39,  38,  38],
         [143, 145, 146,  ...,  40,  39,  38],
         [146, 143, 141,  ...,  39,  39,  39]],

        [[181, 181, 181,  ..., 191, 191, 192],
         [180, 180, 181,  ..., 190, 190, 191],
         [179, 180, 180,  ..., 189, 189, 190],
         ...,
         [147, 147, 148,  ...,   1,   0,   0],
         [148, 148, 1