In [4]:
"""
张量的创建以及初始化。
"""


import torch
import numpy as np
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor

demo = [[1, 2], [2, 3], [2, 5], [0, 29]]

array = np.array(demo)

print(f"通过numpy，将 {type(demo)} --> {type(array)}")

tensor_ = torch.tensor(demo)
_tensor = torch.from_numpy(array)

print(f"通过torch.tensor来实现 {type(demo)} --> {type(tensor_)}")
print(f"通过torch.from_numpy来实现 {type(array)} --> {type(_tensor)}")


# 随机张量
shape = (5, 5,)  # 张量的形状

tensor1 = torch.ones(shape)
print(f"这是随机生成的由一为元素构成的张量：\n {tensor1}")
print("-" * 50)

tensor2 = torch.zeros(shape)
print(f"这是随机生成的由零为元素构成的张量: \n {tensor2}")
print("-" * 50)

tensor3 = torch.rand(shape)
print(f"这是由零到一之间的随机数为元素生成的张量： \n {tensor3}")

print("\n")
print("-" * 70)
print("在原有的张量基础上，创建一个具有相同形状和设备信息的张量：")


# 对原有的张量使用1,0,或者随机张量进行覆盖修改。
list_ = [[1, 2, 3], [2, 6, 7], [3, 4, 6], [5, 6, 10]]
array_ = np.array(list_)
tensor_ = torch.from_numpy(array_)
print(f"--> List: \n{list_}")
print(f"--> Array: \n{array_}")
print(f"--> Tensor: \n{tensor_}")
print("<" + "-" * 70 + ">")
tensor_1 = torch.zeros_like(tensor_)
print(f"将原张量的元素全部变为0： \n{tensor_1}")
print("-" * 70)
tensor_2 = torch.ones_like(tensor_)
print(f"将原张量的元素全部变为1： \n{tensor_2}")
print("-" * 70)
tensor_3 = torch.rand_like(tensor_, dtype=torch.float)
print(f"将原张量的元素变为0-1之间的随机数： \n{tensor_3}")



通过numpy，将 <class 'list'> --> <class 'numpy.ndarray'>
通过torch.tensor来实现 <class 'list'> --> <class 'torch.Tensor'>
通过torch.from_numpy来实现 <class 'numpy.ndarray'> --> <class 'torch.Tensor'>
这是随机生成的由一为元素构成的张量：
 tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
--------------------------------------------------
这是随机生成的由零为元素构成的张量: 
 tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
--------------------------------------------------
这是由零到一之间的随机数为元素生成的张量： 
 tensor([[0.5374, 0.3768, 0.6241, 0.4075, 0.4195],
        [0.2235, 0.0712, 0.6312, 0.7126, 0.7894],
        [0.3703, 0.7517, 0.5220, 0.0088, 0.7283],
        [0.6338, 0.0036, 0.3246, 0.5362, 0.0519],
        [0.3004, 0.0851, 0.2528, 0.1090, 0.1261]])


----------------------------------------------------------------------
在原有的张量基础上，创建一个具有相同形状和

上面的这个代码用于张量的初始化和覆盖已有张量：
A.转换张量：
    1.对于非列表的数据结构：
      a.先将其转换成列表，然后再根据后续的步骤操作进行处理。
    2.对于列表的数据结构：
        a.直接将其转换成张量：
          tensor = torch.tensor(list)
        b.先将其转换成numpy数组，再将其转换成张量：
          array = np.array(list)
          tensor = torch.from_numpy(array)
    3.对于numpy数组的数据结构：
        a.直接将其转换成tensor：
          tensor = torch.from_numpy(array)

B.随机张量：
    <->.首先定义张量的形状：
        shape = (x, y,)
    1.随机元素为0的张量：
      tensor = torch.zeros(shape)
    2.随机元素为[0, 1)之间的浮点数：
      tensor = torch.rand(shape)
    3.随机元素为1的张量：
      tensor = torch.ones(shape)

C.修改覆盖张量：
    <->.修改后的张量形状和设备信息不会发送改变。
    1.将原张量元素全部修改为0：
      new_tensor = torch.zeros_like(base_tensor)
    2.将原张量元素全部修改为[0,1)之间的浮点数：
      new_tensor = torch.rand_like(base_tensor, dtype=torch.gloat)  # 必须显式指定数据类型为浮点数。
    3.将原张量元素全部修改为1：
      new_tensor = torch.ones_like(base_tensor)






In [6]:
"""
张量的属性
"""
import torch


# 形状，数据类型，设备信息。
tensor = torch.rand(3, 4)
tensor_shape = tensor.shape
tensor_dtype = tensor.dtype
tensor_device = tensor.device
print(f"这个随机生成的3X4张量，它的形状是 {tensor_shape} 数据类型是 {tensor_dtype} 设备信息是 {tensor_device}")


这个随机生成的3X4张量，它的形状是 torch.Size([3, 4]) 数据类型是 torch.float32 设备信息是 cpu


这里通过张量的三个属性来获取张量的信息，这三个属性分别为shape，dtype，device。

In [5]:
"""
张量转移
"""
import torch


shape = (3, 3)
tensor = torch.rand(shape, dtype=torch.float, device="cpu")

if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())
    print(f"当前张量位于： {tensor.device}")
else:
    print("加速不可用！")








加速不可用！


此处判断硬件上是否存在加速设备，如果存在就将张量转移到加速设备上。

In [56]:
"""
张量的索引和切片
"""

import torch

# 定义一个列表
lt = [
    [1, 1, 2, 3, 4, 5, 6],
    [2, 1, 2, 3, 4, 5, 6],
    [3, 1, 2, 3, 4, 5, 6],
    [4, 1, 2, 3, 4, 5, 6],
    [5, 1, 2, 3, 4, 5, 6],
    [6, 1, 2, 3, 4, 5, 6]
]
# 将列表转换成张量,这个张量是6 * 7的形状。按照数字的增长顺序来定义，方便观察张量的切片和索引操作。
tr = torch.tensor(lt)
# 打印这个张量
print(tr)

# 打印第一行和最一行
print(tr[0])
print(tr[-1])

# 打印从第二行到倒数第二行
print(tr[1:-1])

# 修改第一行的张量
tr[0, :] = torch.tensor([5, 2, 0, 1, 3, 4, 8])
print(tr)

# 打印张量的第一列
print(tr[:, 0])

# 打印张量的最后一列
print(tr[:, -1])
print(tr[..., -1])

# 打印中间多列
print(tr[..., 0:-1])

# 修改第一列的张量
tr[:, 0] = 10
print(tr)

# 打印第一行，第一列到第二列的张量。
print(tr[0:1, 0:3])


print("------------------分割线---------------------")


# 创建一个三维张量，从列表开始自定义。
li = [
    [
        [1, 2],
        [1, 2],
        [1, 2]
    ],
    [
        [1, 2],
        [1, 2],
        [1, 2]
    ],
    [
        [1, 2],
        [1, 2],
        [1, 2]
    ]
]

te = torch.tensor(li)
# 打印这个三维张量
print(te)
# 降维取出
print(te[..., 0])

print(te[0:2, 0:2, 0])


print("-----------------------分割线---------------------------")
# 对于后面为...的情况出现在高维张量中.

list__ = [
    [
        [1, 2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5, 6]
    ],
    [
        [1, 2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5, 6]
    ],
    [
        [1, 2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5, 6]
    ]
]


tensor__ = torch.tensor(list__)

print(tensor__)

print(tensor__[0:2, ...])

print(tensor__[0])

a = torch.ones(1, 4)
print(a)
print(a[0: 3])
b = torch.tensor([1, 2, 3, 4])
print(b[0:2])
print([1, 2, 3, 4][0:2])

tensor([[1, 1, 2, 3, 4, 5, 6],
        [2, 1, 2, 3, 4, 5, 6],
        [3, 1, 2, 3, 4, 5, 6],
        [4, 1, 2, 3, 4, 5, 6],
        [5, 1, 2, 3, 4, 5, 6],
        [6, 1, 2, 3, 4, 5, 6]])
tensor([1, 1, 2, 3, 4, 5, 6])
tensor([6, 1, 2, 3, 4, 5, 6])
tensor([[2, 1, 2, 3, 4, 5, 6],
        [3, 1, 2, 3, 4, 5, 6],
        [4, 1, 2, 3, 4, 5, 6],
        [5, 1, 2, 3, 4, 5, 6]])
tensor([[5, 2, 0, 1, 3, 4, 8],
        [2, 1, 2, 3, 4, 5, 6],
        [3, 1, 2, 3, 4, 5, 6],
        [4, 1, 2, 3, 4, 5, 6],
        [5, 1, 2, 3, 4, 5, 6],
        [6, 1, 2, 3, 4, 5, 6]])
tensor([5, 2, 3, 4, 5, 6])
tensor([8, 6, 6, 6, 6, 6])
tensor([8, 6, 6, 6, 6, 6])
tensor([[5, 2, 0, 1, 3, 4],
        [2, 1, 2, 3, 4, 5],
        [3, 1, 2, 3, 4, 5],
        [4, 1, 2, 3, 4, 5],
        [5, 1, 2, 3, 4, 5],
        [6, 1, 2, 3, 4, 5]])
tensor([[10,  2,  0,  1,  3,  4,  8],
        [10,  1,  2,  3,  4,  5,  6],
        [10,  1,  2,  3,  4,  5,  6],
        [10,  1,  2,  3,  4,  5,  6],
        [10,  1,  2,  3,  4,  5,  6],
 

张量可以进行类似于numpy数组的索引和切片操作，还可以对其内容进行更新和修改。基本的格式就是类似于列表的索引操作那样，只不过张量可以横竖多个方向，在不同的层面之间用逗号隔开。每个逗号间隔间都可以使用a：b这种操作来对每个不同的层面进行选择。如果只有一个层面，那默认总行开始。张量还可以进行更新和修改，只是修改的内容要和选中的内容形状相同，数据格式相同。：表示全选，而...表示多个连续的:。对于切片出来的张量会比原来的张量低一个维度，如果一个维度只有一个数那可省略不写。对于一维的张量和列表十分类似。


In [15]:
"""
连接张量
"""
import torch

list1 = [1, 1, 1,1]
list2 = [2, 2, 2, 2]
list3 = [3, 3, 3, 3]

ten1 = torch.tensor(list1)
ten2 = torch.tensor(list2)
ten3 = torch.tensor(list3)

print(f"Tensor1 is :\n{ten1}")
print("-" * 70)
print(f"Tensor2 is: \n{ten2}")
print("-" * 70)
print(f"Tensor3 is: \n{ten3}")
print("-" * 70)
L = torch.cat([ten1, ten2, ten3], dim=0)
print(L)
print("-" * 70)

list_ = [
    [1, 2, 3],
    [1, 2, 3],
    [1, 2, 3]
]

_list = [
    [4, 5, 6],
    [4, 5, 6],
    [4, 5, 6]
]

_list_ = [
    [7, 8, 9],
    [7, 8, 9],
    [7, 8, 9]
]

tensor_ = torch.tensor(list_)
_tensor = torch.tensor(_list)
_tensor_ = torch.tensor(_list_)

l = torch.cat([tensor_, _tensor, _tensor_], dim=1)

print("\n\n")
print(tensor_)
print("-" * 70)
print(_tensor)
print("-" * 70)
print(_tensor_)
print("-" * 70)
print(l)


Tensor1 is :
tensor([1, 1, 1, 1])
----------------------------------------------------------------------
Tensor2 is: 
tensor([2, 2, 2, 2])
----------------------------------------------------------------------
Tensor3 is: 
tensor([3, 3, 3, 3])
----------------------------------------------------------------------
tensor([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])
----------------------------------------------------------------------



tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])
----------------------------------------------------------------------
tensor([[4, 5, 6],
        [4, 5, 6],
        [4, 5, 6]])
----------------------------------------------------------------------
tensor([[7, 8, 9],
        [7, 8, 9],
        [7, 8, 9]])
----------------------------------------------------------------------
tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])


相同形状的张量之间可以联结，也就是在相同的维度上，把其他张量的数据从后面加到原来的张量上。类似于在同一维度上的两个列表相加，但是值得注意的是链结完，张量的维度是依然不会变的。方法： Cat = torch.cat([tensor1, tensor2, tensor3], dim=维度)