In [24]:
import torch
# 自动微分

x = torch.ones(5)
y = torch.zeros(3)
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w) + b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)


print(x)
print("-" * 70)
print(y)
print("-" * 70)
print(w)
print("-" * 70)
print(b)
print("-" * 70)
print(torch.matmul(x, w))
print("-" * 70)
print(z)
print("-" * 70)
print(loss)

print("z的梯度函数：")
print(f"Gradient Function for z: {z.grad_fn}")
print("-" * 70)
print("loss的梯度函数：")
print(f"Gradient Function for loss: {loss.grad_fn}")

print("-" * 70 + "\n")

# 反向传播
loss.backward()
print("反向传播后，权重的梯度：")
print(w.grad)
print("-" * 70)
print("反向传播后，偏置的梯度：")
print(b.grad)


print("-" * 70)

# 禁止渐变跟踪
z = torch.matmul(x, w) + b
print(z)  # 有梯度函数，会在反向传播时计算梯度。
print("-" * 70)
with torch.no_grad():
    z = torch.matmul(x, w) + b
    print(z)  # 没有梯度函数，反向传播后不会发生改变。

# 禁用渐变跟踪的另一种方法
z = torch.matmul(x, w) + b
z_det = torch.detach(z)
"""打印是否开启自动微分"""
print(z_det.requires_grad)





tensor([1., 1., 1., 1., 1.])
----------------------------------------------------------------------
tensor([0., 0., 0.])
----------------------------------------------------------------------
tensor([[ 2.7350,  0.8508, -0.3389],
        [ 0.3362, -0.5206,  0.5923],
        [-2.8467,  0.3082,  1.0897],
        [-1.0334,  0.1714, -0.3709],
        [-0.2140, -0.3185,  0.5474]], requires_grad=True)
----------------------------------------------------------------------
tensor([-0.2412, -1.3444,  1.4236], requires_grad=True)
----------------------------------------------------------------------
tensor([-1.0229,  0.4913,  1.5195], grad_fn=<SqueezeBackward4>)
----------------------------------------------------------------------
tensor([-1.2641, -0.8531,  2.9431], grad_fn=<AddBackward0>)
----------------------------------------------------------------------
tensor(1.1994, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
z的梯度函数：
Gradient Function for z: <AddBackward0 object at 0x7ebcc8b2f1c0>
-

In [2]:
t = torch.tensor([
    [1, 2],
    [1, 2]
], dtype=torch.float)

t_ = torch.tensor([
    [1, 2],
    [1, 2]
], requires_grad=True, dtype=torch.float)

print(f"普通张量： \n{t}")
print("-" * 70)
print(f"自动微分张量: \n{t_}")

from torchvision.io import read_image


print(read_image("/home/SayMyName/桌面/GitHub/MyCode/DeepLearn/PyTorch/PyTorch_code_3_image_dir/test1_cat.jpg"))



普通张量： 
tensor([[1., 2.],
        [1., 2.]])
----------------------------------------------------------------------
自动微分张量: 
tensor([[1., 2.],
        [1., 2.]], requires_grad=True)
tensor([[[163, 163, 163,  ..., 174, 174, 175],
         [162, 162, 163,  ..., 173, 173, 174],
         [161, 162, 162,  ..., 172, 172, 173],
         ...,
         [140, 140, 141,  ...,  71,  70,  70],
         [140, 141, 143,  ...,  72,  71,  70],
         [143, 140, 138,  ...,  71,  71,  71]],

        [[169, 169, 169,  ..., 181, 181, 182],
         [168, 168, 169,  ..., 180, 180, 181],
         [167, 168, 168,  ..., 179, 179, 180],
         ...,
         [144, 144, 145,  ...,  39,  38,  38],
         [143, 145, 146,  ...,  40,  39,  38],
         [146, 143, 141,  ...,  39,  39,  39]],

        [[181, 181, 181,  ..., 191, 191, 192],
         [180, 180, 181,  ..., 190, 190, 191],
         [179, 180, 180,  ..., 189, 189, 190],
         ...,
         [147, 147, 148,  ...,   1,   0,   0],
         [148, 148, 1

开启了requires_grad的张量会记入梯度的计算，从而可以反向传播优化参数。对loss使用backward ()方法进行反向传播更新参数
公式： 新参数 = 旧参数 - 学习率 * 梯度
开启新的一轮训练前要清除梯度。
在向前传播或者推理时冻结参数可以使用 torch.no_grad 或者 torch.detach(z).